# Generated by Django 3.2.8 on 2021-10-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20211005_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
