# Generated by Django 3.2.8 on 2021-10-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('SE', 'secondary'), ('S', 'success'), ('DD', 'danger'), ('W', 'warning'), ('I', 'info'), ('L', 'light'), ('D', 'dark')], max_length=2),
        ),
    ]
